### ISSUE TITLE
Enable scriptable output

### ISSUE THREAD

**Issue by baschny** [kitzberger/cli-toolbox#4]
If I want to use the list of uids in a script, I have to strip useless output from the stdout manually:
```
$ bin/typo3 toolbox:tree 588

 Determining pages tree of root id: 588
 588,596,597,598,599,1541,600,601,602,603,604,605,5405,607,610,644,645,646,647,648,649,611,612,5660,613,614,615,616,617,618,619,620,621,622,623,624,625,626,627,628,629,630,631,632,633,634,635,636,637,638,639,640,641,642,643,1472,595,5490,1474,593
```

Would be great if I could use the `-q` (quiet) flag to get just the list so that I can use that in a script, i.e.:
```
pids=$(bin/typo3 toolbox:tree 588 -q)
mysql -BNe "SELECT COUNT(*) FROM pages where uid in ($pids)"
```
Or something like that... 

Currently the `-q` flag simply strips all output (even the important one). :)

**Comment by baschny** [comment]
Maybe even have an option to output the list in different ways, i.e. "comma separated" by default but also possible to get "one ID per line" (i.e. easier to implement a `for pid in $(bin/typo3 toolbox:tree 588); do ...` script).

**Comment by kitzberger** [comment]
@baschny, great idea! Please have a look at #5
